stages:
  - init
  - build
  - test
  - sast
  - run-junit
  - tagging

include:
  - template: Jobs/SAST.gitlab-ci.yml

variables:
  SEARCH_MAX_DEPTH: 10
  PACKAGE_NAME: "sample"
  PACKAGE_VERSION: "0.0.1-SNAPSHOT"
  PACKAGE_REGISTRY_URL: "https://gitlab.com/api/v4/projects/38062833/packages/generic"


# Cache definitions
cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/
    - target/


tag:
  stage: init
  script:
    - PACKAGE_VERSION=$(echo $CI_COMMIT_SHA | cut -c -4)
    - echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> build.env
  artifacts:
    expire_in: 1 days
    reports:
      dotenv: build.env


# Build Stage
build:
  image: maven:3.6-jdk-8-slim
  stage: build
  cache:
    key: maven-dependencies
    paths:
      - .m2/repository/
  script:
    - mvn clean
    - mvn package -Dmaven.repo.local=./.m2/repository
  artifacts:
    paths:
      - .m2/
      - target/sample-0.0.1-SNAPSHOT.jar
  allow_failure: false

# SpotBugs SAST
spotbugs-sast:
  dependencies:
    - build
  variables:
    MAVEN_REPO_PATH: $CI_PROJECT_DIR/.m2/repository
    COMPILE: "false"
  cache:
    key: sast-cache
    paths:
      - .m2/repository/
      - target/
  script:
    - echo "Current working directory:"
    - pwd
    - echo "Files in the current directory:"
    - ls -l
    - echo "Attempting to display gl-sast-report.json:"
    - cat gl-sast-report.json || echo "SAST report not found."
  artifacts:
    reports:
      sast: gl-sast-report.json
  allow_failure: false

# SAST
sast:
  stage: test
  allow_failure: true
  artifacts:
    paths: [gl-sast-report.json]
    reports:
      sast: gl-sast-report.json

# Validate Reports
send-reports:
  image: ubuntu:20.04
  stage: sast
  artifacts:
    reports:
      sast: gl-sast-report.json
  script:
    - bash -x check_sast_exit.sh

# JUnit Tests
run-junit-tests:
  image: maven:3.6-jdk-8-slim
  stage: run-junit
  cache:
    key: junit-tests-cache
    paths:
      - .m2/repository/
      - target/
  script:
    - mvn test
    - bash validate_junit_tests.sh
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    reports:
      junit: target/surefire-reports/*.xml
  allow_failure: false
  needs: ["build", "send-reports"]




# Tag Artifact Stage
tag-code:
  image: curlimages/curl:latest
  stage: tagging
  dependencies:
    - build
  cache:
    key: artifact-tagging-cache
    paths:
      - target/
  script:
    - |
      if [ -z "$CI_COMMIT_TAG" ]; then
        echo "Error: Tagging is required before merging to main."
        exit 1
      fi

      echo "Tagging artifact with tag: $CI_COMMIT_TAG"
      mv target/sample-0.0.1-SNAPSHOT.jar target/sample-${CI_COMMIT_TAG}.jar

      echo "Uploading artifact to package registry"
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --upload-file "target/sample-${CI_COMMIT_TAG}.jar" \
           "$PACKAGE_REGISTRY_URL/$PACKAGE_NAME/$PACKAGE_VERSION/sample-${CI_COMMIT_TAG}.jar"
  only: 
    - tags


# Tag Artifact Stage
tag-artifact:
  image: curlimages/curl:latest
  stage: tagging
  dependencies:
    - build
  cache:
    key: artifact-tagging-cache
    paths:
      - target/
  script:
    - |
      if [ -z "$PACKAGE_VERSION" ]; then
        echo "Error: Tagging is required before merging to main."
        exit 1
      fi

      echo "Tagging artifact with tag: $PACKAGE_VERSION"
      mv target/sample-0.0.1-SNAPSHOT.jar target/sample-${PACKAGE_VERSION}.jar

      echo "Uploading artifact to package registry"
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --upload-file "target/sample-${PACKAGE_VERSION}.jar" \
           "$PACKAGE_REGISTRY_URL/$PACKAGE_NAME/$PACKAGE_VERSION/sample-${PACKAGE_VERSION}.jar"
